import { MCPServerConfig, TransportType, MCPTool, MCPResource } from '@/types/mcp';
import yaml from 'js-yaml';

interface MCPServerManifest {
	name: string;
	description?: string;
	version: string;
	command?: string;
	args?: string[];
	env?: Record<string, string>;
}

/**
 * Generates an MCP server configuration file (Claude configuration format)
 */
export function generateMCPServerConfig(
	server: MCPServerConfig
): Record<string, any> {
	const config: Record<string, any> = {
		type: 'stdio',
	};

	if (server.transportType === 'sse') {
		config.type = 'sse';
		config.url = server.baseUrl;
	} else if (server.transportType === 'http_stream') {
		config.type = 'sse';
		config.url = server.baseUrl;
	} else if (server.transportType === 'websocket') {
		config.type = 'websocket';
		config.url = server.baseUrl;
	}

	return {
		[server.slug]: {
			...config,
			env: {
				MCP_API_KEY: server.apiKey,
				TIMEOUT_MS: String(server.timeoutMs),
				MAX_CONNECTIONS: String(server.maxConnections),
			},
		},
	};
}

/**
 * Generates a Claude configuration YAML with MCP server
 */
export function generateClaudeConfig(server: MCPServerConfig): string {
	const config = {
		mcpServers: generateMCPServerConfig(server),
	};

	return yaml.dump(config, { indent: 2 });
}

/**
 * Generates a Python MCP server client
 */
export function generatePythonClient(server: MCPServerConfig): string {
	return `#!/usr/bin/env python3
"""
MCP Client for ${server.name}
Auto-generated by mcpify
"""

import asyncio
import json
from contextlib import asynccontextmanager
${server.transportType === 'websocket' ? 'import websockets' : 'import aiohttp'}

class MCPClient:
    def __init__(self, api_key: str, base_url: str):
        self.api_key = api_key
        self.base_url = base_url
        self.timeout = ${server.timeoutMs} / 1000

    @asynccontextmanager
    async def connect(self):
${server.transportType === 'websocket'
			? `        async with websockets.connect(self.base_url) as websocket:
            yield websocket`
			: `        async with aiohttp.ClientSession() as session:
            yield session`
		}

    async def list_tools(self):
        """List available tools"""
        ${server.transportType === 'websocket'
			? `async with self.connect() as ws:
            await ws.send(json.dumps({'method': 'tools/list'}))
            response = await ws.recv()
            return json.loads(response)`
			: `async with self.connect() as session:
            async with session.get(
                f"{self.base_url}/tools",
                headers={'Authorization': f'Bearer {self.api_key}'},
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                return await resp.json()`
		}

    async def call_tool(self, tool_name: str, arguments: dict):
        """Call a tool with arguments"""
        ${server.transportType === 'websocket'
			? `async with self.connect() as ws:
            message = {
                'method': 'tools/call',
                'params': {
                    'name': tool_name,
                    'arguments': arguments
                }
            }
            await ws.send(json.dumps(message))
            response = await ws.recv()
            return json.loads(response)`
			: `async with self.connect() as session:
            async with session.post(
                f"{self.base_url}/tools/{tool_name}",
                json={'arguments': arguments},
                headers={'Authorization': f'Bearer {self.api_key}'},
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                return await resp.json()`
		}

if __name__ == '__main__':
    client = MCPClient(
        api_key='${server.apiKey}',
        base_url='${server.baseUrl}'
    )
`;
}

/**
 * Generates a Node.js/TypeScript MCP server client
 */
export function generateNodeClient(server: MCPServerConfig): string {
	return `/**
 * MCP Client for ${server.name}
 * Auto-generated by mcpify
 */

${server.transportType === 'websocket' ? "import WebSocket from 'ws';" : "import fetch from 'node-fetch';"}

interface MCPClientOptions {
  apiKey: string;
  baseUrl: string;
  timeout?: number;
}

class MCPClient {
  private apiKey: string;
  private baseUrl: string;
  private timeout: number;

  constructor(options: MCPClientOptions) {
    this.apiKey = options.apiKey;
    this.baseUrl = options.baseUrl;
    this.timeout = options.timeout || ${server.timeoutMs};
  }

  async listTools(): Promise<any[]> {
    ${server.transportType === 'websocket'
			? `const ws = new WebSocket(this.baseUrl);
    return new Promise((resolve, reject) => {
      ws.on('open', () => {
        ws.send(JSON.stringify({ method: 'tools/list' }));
      });
      ws.on('message', (data) => {
        const response = JSON.parse(data.toString());
        resolve(response.tools);
        ws.close();
      });
      ws.on('error', reject);
    });`
			: `const response = await fetch(\`\${this.baseUrl}/tools\`, {
      headers: {
        'Authorization': \`Bearer \${this.apiKey}\`,
        'Content-Type': 'application/json',
      },
      timeout: this.timeout,
    });
    const data = await response.json();
    return data.tools;`
		}
  }

  async callTool(toolName: string, arguments_: Record<string, any>): Promise<any> {
    ${server.transportType === 'websocket'
			? `const ws = new WebSocket(this.baseUrl);
    return new Promise((resolve, reject) => {
      ws.on('open', () => {
        ws.send(JSON.stringify({
          method: 'tools/call',
          params: {
            name: toolName,
            arguments: arguments_,
          },
        }));
      });
      ws.on('message', (data) => {
        const response = JSON.parse(data.toString());
        resolve(response.content);
        ws.close();
      });
      ws.on('error', reject);
    });`
			: `const response = await fetch(\`\${this.baseUrl}/tools/\${toolName}\`, {
      method: 'POST',
      headers: {
        'Authorization': \`Bearer \${this.apiKey}\`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ arguments: arguments_ }),
      timeout: this.timeout,
    });
    const data = await response.json();
    return data.content;`
		}
  }
}

export default MCPClient;
`;
}

/**
 * Generates a README with instructions
 */
export function generateReadme(server: MCPServerConfig): string {
	return `# ${server.name} - MCP Server

> Auto-generated MCP server for ${server.name}

## Description

${server.description || 'No description provided'}

## Setup

### Installation

\`\`\`bash
npm install mcpify-client
\`\`\`

### Configuration

Add to your Claude configuration file:

\`\`\`yaml
${generateClaudeConfig(server)}
\`\`\`

## Usage

### Python

\`\`\`python
import asyncio
from mcpify import MCPClient

client = MCPClient(
    api_key='${server.apiKey}',
    base_url='${server.baseUrl}'
)

async def main():
    tools = await client.list_tools()
    print(f"Available tools: {len(tools)}")
    
asyncio.run(main())
\`\`\`

### JavaScript/TypeScript

\`\`\`typescript
import MCPClient from 'mcpify-client';

const client = new MCPClient({
  apiKey: '${server.apiKey}',
  baseUrl: '${server.baseUrl}',
});

const tools = await client.listTools();
console.log(\`Available tools: \${tools.length}\`);
\`\`\`

## Available Tools

${server.enabledTools.map((tool) => `- \`${tool}\``).join('\n')}

## Resources

${server.enabledResources.length > 0 ? server.enabledResources.map((resource) => `- \`${resource}\``).join('\n') : 'No resources available'}

## Transport Type

\`${server.transportType}\`

## API Key

Your API key is: \`${server.apiKey}\`

Keep this key secure and never commit it to version control.

## Support

For issues or questions, visit: https://mcpify.app/support
`;
}

export function generateDockerfile(server: MCPServerConfig): string {
	return `FROM node:20-slim

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

ENV MCP_API_KEY=${server.apiKey}
ENV MCP_BASE_URL=${server.baseUrl}
ENV MCP_TIMEOUT_MS=${server.timeoutMs}

EXPOSE 3000

CMD ["npm", "start"]
`;
}
